let shopItemsData = [
  {
    id: "shirt1001",
    name: "Men’s Gucci Shirt ",
    price: 9000,
    desc: "Pure Silk shirt, Blue, Plus Size S-7",
    pid: "#SHT1001",
    img: "images/products/shirt1001.jpg",
  },
  {
    id: "shirt1002",
    name: "Gucci Designer Shirt",
    price: 9000,
    desc: "Pure Silk shirt, White, Plus Size S-6",
    pid: "#SHT1002",
    img: "images/products/shirt1002.jpg",
  },
  {
    id: "shirt1003",
    name: "Men's Designer Shirt",
    price: 9500,
    desc: "Pure Silk shirt, White, Plus Size S-6",
    pid: "#SHT1003",
    img: "images/products/shirt1003.jpg",
  },
  {
    id: "shirt1004",
    name: "Thick R-Neck Top",
    price: 12000,
    desc: "Embroided, black, Plus Size S-8",
    pid: "#SHT1004",
    img: "images/products/shirt1004.jpg",
  },
  {
    id: "shirt1005",
    name: "R-neck Designer Polo",
    price: 12500,
    desc: "Pure cotton, White, all sizes available",
    pid: "#SHT1005",
    img: "images/products/shirt1005.jpg",
  },
  {
    id: "shirt1006",
    name: "Designer Jacket",
    price: 15000,
    desc: "Pure cotton, Brown, all sizes",
    pid: "#SHT1006",
    img: "images/products/shirt1006.jpg",
  },
  {
    id: "shirt1007",
    name: "Louis-Vuitton Polo",
    price: 8500,
    desc: "Pure Cotton, Black or White, all sizes",
    pid: "#SHT1007",
    img: "images/products/shirt1007.jpg",
  },
  {
    id: "shirt1008",
    name: "Gucci Sleeveless Top",
    price: 7000,
    desc: "Pure cotton, Green, free size",
    pid: "#SHT1008",
    img: "images/products/shirt1008.jpg",
  },
  {
    id: "shirt1009",
    name: "Burberry T-Shirt",
    price: 9000,
    desc: "Pure Cotton, Yellow/Green/Orange/White, Plus size S-7",
    pid: "#SHT1009",
    img: "images/products/shirt1009.jpg",
  },
  {
    id: "shirt1010",
    name: "Denim Combat Jacket",
    price: 15000,
    desc: "Logo patch jacket, Black/Grey, all sizes ",
    pid: "#SHT1010",
    img: "images/products/shirt1010.jpg",
  },
  {
    id: "pants2001",
    name: "Trendy Denim Pant",
    price: 16500,
    desc: "Pure Jean pant, Blue, all sizes available",
    pid: "#PNT2001",
    img: "images/products/pants2001.jpg",
  },
  {
    id: "pants2002",
    name: "Unisex  Prada Pants",
    price: 15000,
    desc: "Pure swede Pant, Black, all sizes available",
    pid: "#PNT2002",
    img: "images/products/pants2002.jpg",
  },
  {
    id: "shoes3001",
    name: "Nike Air Sneakers",
    price: 20000,
    desc: "Original nike air sneakers, White, all sizes",
    pid: "#SHO3001",
    img: "images/products/shoes3001.jpg",
  },
  {
    id: "shoes3002",
    name: "Nike Air Sneakers",
    price: 18500,
    desc: "Original nike air sneakers, White and blue, all sizes",
    pid: "#SHO3002",
    img: "images/products/shoes3002.jpg",
  },
  {
    id: "sweat4001",
    name: "Men's Bomber Jacket",
    price: 25000,
    desc: "Long Sleeve Stand Collar, Black, all sizes",
    pid: "#SWT4001",
    img: "images/products/sweat4001.jpg",
  },
  {
    id: "sweat4002",
    name: "Men's Bomber Jacket",
    price: 30000,
    desc: "Long Sleeve Stand Collar, Green, all sizes",
    pid: "#SWT4002",
    img: "images/products/sweat4002.jpg",
  },
  {
    id: "sweat4003",
    name: "Men’s Sweat Shirt",
    price: 18750,
    desc: "Pure Wool Shirt, White, Size S-8",
    pid: "#SWT4003",
    img: "images/products/sweat4003.jpg",
  },
  {
    id: "sweat4004",
    name: "Sleeveless Sweater",
    price: 10000,
    desc: "Pure cotton wool top, armless, multi-colour",
    pid: "#SWT4004",
    img: "images/products/sweat4004.jpg",
  },
  {
    id: "sweat4005",
    name: "Sleeveless Sweater",
    price: 11500,
    desc: "Pure cotton wool top, armless, White + Red",
    pid: "#SWT4005",
    img: "images/products/sweat4005.jpg",
  },
  {
    id: "sweat4006",
    name: "Unisex Denim Jacket",
    price: 23000,
    desc: "Original denim jeann Blue, all sizes",
    pid: "#SWT4006",
    img: "images/products/sweat4006.jpg",
  },
  {
    id: "sweat4007",
    name: "Men’s Sweat Shirt",
    price: 18000,
    desc: "Pure Wool Shirt, White, Size S-8",
    pid: "#SWT4007",
    img: "images/products/sweat4007.jpg",
  },
  {
    id: "sweat4008",
    name: "Men's Bomber Jacket",
    price: 25000,
    desc: "Long Sleeve Stand Collar, Green, all sizes",
    pid: "#SWT4008",
    img: "images/products/sweat4008.jpg",
  },
  {
    id: "sweat4009",
    name: "Designer Hoodie",
    price: 12000,
    desc: "Cotton, Hoodie, White, Long-sleeve, all sizes",
    pid: "#SWT4009",
    img: "images/products/sweat4009.jpg",
  },
  {
    id: "bpack6001",
    name: "Lacoste Backpack",
    price: 9000,
    desc: "Original Lacoste back pacl, Leather, medium size",
    pid: "#BPK6001",
    img: "images/products/bpack6001.jpg",
  },
  {
    id: "watch5001",
    name: "Patek Philippe Watch",
    price: 262500,
    desc: "Chain watch, 46mm, Rose Gold, Silver, Gold",
    pid: "#WAT5001",
    img: "images/products/watch5001.jpg",
  },
  {
    id: "watch5002",
    name: "Rolex - Couple Set",
    price: 90000,
    desc: "Chain watch, 38mm, Gold, Silver , Rose Gold",
    pid: "#WAT5002",
    img: "images/products/watch5002.jpg",
  },
  {
    id: "watch5003",
    name: "Patek Philippe Watch",
    price: 280000,
    desc: "Chain watch, 46mm, Rose Gold, Silver, Gold",
    pid: "#WAT5003",
    img: "images/products/watch5003.jpg",
  },
  {
    id: "watch5004",
    name: "olex - Couple Set",
    price: 120000,
    desc: "hain watch, 38mm, Gold, Silver , Rose Gold",
    pid: "#WAT5004",
    img: "images/products/watch5004.jpg",
  },
  {
    id: "trlbx8001",
    name: "Travel Box",
    price: 35000,
    desc: "Original travel box with wheels, Green, large size",
    pid: "#TBX8001",
    img: "images/products/trlbx8001.jpg",
  },
  {
    id: "track7001",
    name: "Luxury Unisex Track",
    price: 22500,
    desc: "Pure cotton, Grey/White, Plus Size S-7",
    pid: "#TRK7001",
    img: "images/products/track7001.jpg",
  },
  {
    id: "track7002",
    name: "Luxury Unisex Combo",
    price: 20000,
    desc: "Pure cotton, Grey/White, Plus Size S-7",
    pid: "#TRK7002",
    img: "images/products/track7002.jpg",
  },
  {
    id: "track7003",
    name: "Luxury Unisex Combo",
    price: 20000,
    desc: "Pure cotton, Grey/White, Plus Size S-7",
    pid: "#TRK7003",
    img: "images/products/track7003.jpg",
  }
];
